server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** # 商品服务
    user-service: /user/** # 用户服务
    auth-service: /auth/** # 授权中心
  add-host-header: true # 转发的时候，携带原本head头信息
  sensitive-headers: # 过滤掉敏感的头信息,设置为null，则不会禁止
ribbon:
  ConnectTimeout: 100000 # 连接超时时间(ms)
  ReadTimeout: 600000 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 100000 # 熔断超时时长：5000ms
# 配置
leyou:
  jwt:
    pubKeyPath: /Users/damon/up/learning/upload/jwt/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth/accredit
      - /api/user/register
      - /api/user/check
      - /api/user/sms
      - /api/user/queryUserByUsernameAndPassword
      - /api/item
      - /api/search
