server:
  port: 8085
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456
  redis:
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  sms:
    accessKeyId: LTAI4G22FocJNF4NyU7ZZm6R # 你自己的accessKeyId
    accessKeySecret: Ue70oEh2526mCQ0sX0DwBvwvR0nrr5 # 你自己的AccessKeySecret
    signName: ABC商城 # 签名名称
    templateCode: SMS_206738024 # 模板名称